### ISSUE TITLE
Make indexing by Googlebot impossible

### ISSUE THREAD

**Issue by stephanegg** [JPeer264/ngx-tooltip-server#2]
Googlebot is using Chrome v41 to crawl websites. If you run an angular 5 lib with ngx tooltip server you will come across the below errors which therefore make the indexing impossible. 

![screen shot 2018-04-23 at 23 22 15](https://user-images.githubusercontent.com/31510240/39156461-1dd8bd04-474e-11e8-8ba6-e18a0b2513be.png)

![screen shot 2018-04-23 at 23 22 31](https://user-images.githubusercontent.com/31510240/39156464-215a9682-474e-11e8-89df-2f2f52188b3b.png)

Expected behavior: es5 module transpiled picked up to make indexing possible.

**Comment by JPeer264** [comment]
Hey @stephanegg, thanks for your issue. 

I think you should use this file instead: `ngx-tooltip-server.es5.js`. Since `v1.1.0` I am following the [Angular Package Format (APF)](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview) which made it easy to specify the needed format.

Following configuration in your `tsconfig.json` may solve your issue:
```json
{
  "compilerOptions": {
    ...
    "module": "es2015",
    "target": "es5",
    ...
},
```

**Comment by stephanegg** [comment]
Thank you @JPeer264 for the quick answer. Indeed, I had the below config:

`{
  "compilerOptions": {
    ...
    "module": "es6",
    "target": "es5",
    ...
},`

**Comment by JPeer264** [comment]
Glad it solved your issue
